spring:
  application:
    name: code-genie-screenshot
  profiles:
    active: local
server:
  port: 8127
  servlet:
    context-path: /api

# Dubbo
dubbo:
  registry:
    address: nacos://192.168.6.128:8848
    register-mode: instance
  protocol:
    name: tri
    port: 50052
  consumer:
    timeout: 120000
  provider:
    timeout: 120000
