spring:
  application:
    name: code-genie-user
  # session
  session:
    redis:
      namespace: spring:session
    # 30 days expire
    timeout: 2592000
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}
  # redis
  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      database: 0
      password:
  profiles:
    active: local
server:
  port: 8124
  servlet:
    context-path: /api
    # 30 days expire
    session:
      cookie:
        max-age: 2592000
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.hgl.codegenie.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# Dubbo
dubbo:
  registry:
    address: nacos://192.168.6.128:8848
    register-mode: instance
  protocol:
    name: tri
    port: 50051
  consumer:
    timeout: 60000
  provider:
    timeout: 60000
